GET http://localhost:3000/v1/tweets
Accept: application/json

###
POST http://localhost:3000/v1/tweets
Accept: application/json

###
GET http://localhost:3000/v1/tweets/5eb65489e1590e01f0c95697
Accept: application/json

###
DELETE http://localhost:3000/v1/tweets/1
Accept: application/json

###